### ISSUE TITLE
Rewrite to separate IBC and DE

### ISSUE THREAD

**Issue by dpsanders** [JuliaIntervals/CharibdeOptim.jl#49]
The implementations of IBC and DE should be separated out.
In principle they should not need to know anything about channels and passing information to anywhere.

That can possibly be controlled separately by controllers that are able to run steps of each method?

**Comment by yashcodes** [comment]
The user can use IBC separately (as shown in testset "Optimising by Interval Branch and Contract Algorithm").
But in the current version, DE cant be used as IBC separately which feature can be added.
